version: "3.9"

name: "rgd-bot"

services:
  bot-app:
    container_name: '${COMPOSE_PROJECT_NAME}_bot'
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .production.env
    restart: unless-stopped
    ports:
      - "1984:1984"
    depends_on:
      - redis
      - postgres
    networks:
      - rgd-bot

  postgres:
    image: postgres:16-alpine
    container_name: '${COMPOSE_PROJECT_NAME}_postgres'
    environment:
      POSTGRES_USER: rgdbot_dev
      POSTGRES_PASSWORD: rgdbot
      POSTGRES_DB: rgdbot_dev
    logging:
      options:
        max-size: 10m
        max-file: "3"
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - rgdbot_database:/var/lib/postgresql/data
    networks:
      - rgd-bot

  redis:
    image: 'redis:alpine'
    container_name: '${COMPOSE_PROJECT_NAME}_redis'
    command: 'redis-server --appendonly yes'
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - rgdbot_redis:/data
    networks:
      - rgd-bot

volumes:
  rgdbot_database:
  rgdbot_redis:

networks:
  rgd-bot: