version: '3.9'

name: 'rgd-bot'

services:
  bot-app:
    container_name: 'rgd-bot'
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    env_file:
      - .production.env
    restart: unless-stopped
    network_mode: host
