version: '3.9'

name: 'rgd-bot'

services:
  bot-app:
    container_name: '${COMPOSE_PROJECT_NAME}_bot'
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .production.env
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
    network_mode: host
